export const SET_SPIDER_BUGS = 'setSpiderBugs'
export const APPEND_SPIDER_BUGS = 'appendSpiderBugs'
export const SET_SPIDER_LIBRARY = 'setSpiderLibrary'
export const SET_SPIDER_PAGE = "setSpiderPage"
export const SET_SPIDER_PAGINATION = 'setSpiderPagination'

export const SET_CLASSIFIER_SELECT = 'setClassifierSelect'
export const SET_CLASSIFIER_CATEGORYS = 'setClassifierCategorys'
export const SET_CLASSIFIER_RESULTS = 'setClassifierResults'
export const SET_CLASSIFIER_TAXONOMYS = 'setClassifierTaxonomys'
export const APPEND_CLASSIFIER_TAXONOMY = 'appendClassifierTaxonomy'
export const UPDATE_CLASSIFIER_TAXONOMY = 'updateClassifierTaxonomy'
export const UPDATE_CLASSIFIER_TAXONOMY_CATEGORY = 'updateClassifierTaxonomyCategory'
export const APPEND_CLASSIFIER_TAXONOMY_CATEGORY = 'appendClassifierTaxonomyCategory'
export const DELETE_CLASSIFIER_TAXONOMY_CATEGORY = 'deleteClassifierTaxonomyCategory'

export const SET_RUD_OPERATOR_OPERATORS = 'setRUDOperatorOperators'
export const APPEND_RUD_OPERATOR_OPERATOR = 'appendRUDOperatorOperator'
export const UPDATE_RUD_OPERATOR_OPERATOR = 'updateRUDOperatorOperator'
export const SET_RUD_OPERATOR_SEARCH = 'setRUDOperatorSearch'
export const SET_RUD_OPERATOR_PAGINATION = 'setRUDOperatorPagination'

export const SET_MUTATE_METHOD_MUTATE_METHODS = 'setMutateMethodMutateMethods'
export const APPEND_MUTATE_METHOD_MUTATE_METHOD = 'appendMutateMethodMutateMethod'
export const UPDATE_MUTATE_METHOD_MUTATE_METHOD = 'updateMutateMethodMutateMethod'
export const SET_MUTATE_METHOD_ALL_MUTATE_METHODS_CHECKED = 'setMutateMethodAllMutateMethodsChecked'
export const SET_MUTATE_METHOD_SEARCH = 'setMutateMethodSearch'
export const SET_MUTATE_METHOD_PAGINATION = 'setMutateMethodPagination'

export const SET_CORPUS_SET_MODEL = 'setCorpusSetModel'
export const SET_CORPUS_SET_MODEL_LAYERS = 'setCorpusSetLayers'
export const SET_CORPUS_SET_MODEL_SUMMARY = 'setCorpusSetModelSummary'
export const SET_CORPUS_SET_DATASET = 'setCorpusSetDataset'
export const SET_CORPUS_SET_DATAS = 'setCorpusSetDatas'
export const SET_CORPUS_SET_SELECTED_DATA = 'setCorpusSetSelectedData'
export const SET_CORPUS_SET_SELECTED_IMAGE_BASE64 = 'setCorpusSetSelectedImageBase64'
export const SET_CORPUS_SET_SEARCH = 'setCorpusSetSearch'
export const SET_CORPUS_SET_PAGINATION = 'setCorpusSetPagination'

export const SET_DIFF_TEST_SETTING = 'setDiffTestSetting'
export const SET_DIFF_TEST_STATE = 'setDiffTestState'
export const EMPTY_DIFF_TEST_RESULTS = 'emptyDiffTestResults'
export const APPEND_DIFF_TEST_RESULTS = 'appendDiffTestResults'
export const APPEND_DIFF_TEST_SUSPECTS = 'appendDiffTestSuspects'
export const SET_DIFF_TEST_SUFFICIENCY = 'setDiffTestSufficiency'